import { Weapons } from "./index";

export const weapons: Weapons = [
  {
    id: "w00",
    name: "Great Sword",
    icon: "great_sword",
    image_prefix: "two",
    skins: [],
  },
  {
    id: "w01",
    name: "Sword and Shield",
    icon: "sword_and_shield",
    image_prefix: "one",
    skins: [],
  },
  {
    id: "w02",
    name: "Hammer",
    icon: "hammer",
    image_prefix: "ham",
    skins: [],
  },
  {
    id: "w03",
    name: "Lance",
    icon: "lance",
    image_prefix: "lan",
    skins: [],
  },
  {
    id: "w04",
    name: "heavy Bowgun",
    icon: "heavy_bowgun",
    image_prefix: "hbg",
    skins: [],
  },
  {
    id: "w06",
    name: "Light Bowgun",
    icon: "light_bowgun",
    image_prefix: "lbg",
    skins: [],
  },
  {
    id: "w07",
    name: "Long Sword",
    icon: "long_sword",
    image_prefix: "swo",
    skins: [],
  },
  {
    id: "w08",
    name: "Switch Axe",
    icon: "switch_axe",
    image_prefix: "axe",
    skins: [],
  },
  {
    id: "w09",
    name: "Gunlance",
    icon: "gunlance",
    image_prefix: "gun",
    skins: [],
  },
  {
    id: "w10",
    name: "Bow",
    icon: "bow",
    image_prefix: "bow",
    skins: [],
  },
  {
    id: "w11",
    name: "Dual Blades",
    icon: "dual_blades",
    image_prefix: "sou",
    skins: [],
  },
  {
    id: "w12",
    name: "Hunting Horn",
    icon: "hunting_horn",
    image_prefix: "hue",
    skins: [],
  },
  {
    id: "w13",
    name: "Insect Glaive",
    icon: "insect_glaive",
    image_prefix: "rod",
    skins: [],
  },
  {
    id: "w14",
    name: "Charge Blade",
    icon: "charge_blade",
    image_prefix: "gaxe",
    skins: [],
  },
];
